[package]
name = "irc_server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.53", features = ["full"] }
bytes = {version = "1.12"}
log = {version = "0.4"}
env_logger = {version = "0.11"}
toml = "1.1"
serde = "1.0"
serde_derive = "1.0"
once_cell = "1.21"
bitflags = "2.13"
rand = "0.10"
irc_proto = { path = "irc_proto"}
chrono = "0.4"

[workspace]
members = [ "irc_proto"]
